"""init tables: gmail_tokens, emails, classifications, gmail_labels

Revision ID: 98a7eb6f5ca8
Revises: 
Create Date: 2026-07-30 00:29:09.023815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a7eb6f5ca8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gmail_message_id', sa.Text(), nullable=False),
    sa.Column('gmail_thread_id', sa.Text(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), server_default='', nullable=False),
    sa.Column('snippet', sa.Text(), server_default='', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','replied','no_reply_needed')", name='ck_emails_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gmail_message_id', name='uq_emails_user_gmail_message')
    )
    op.create_index('ix_emails_user_pending', 'emails', ['user_id', 'status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_emails_user_received_at', 'emails', ['user_id', 'received_at'], unique=False)
    op.create_table('gmail_labels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label_name', sa.Text(), nullable=False),
    sa.Column('label_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'label_name')
    )
    op.create_table('gmail_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.Text(), nullable=False),
    sa.Column('gmail_address', sa.Text(), nullable=False),
    sa.Column('history_id', sa.BigInteger(), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('gmail_address', name='uq_gmail_tokens_gmail_address')
    )
    op.create_index('ix_gmail_tokens_watch_expiration', 'gmail_tokens', ['watch_expiration'], unique=False)
    op.create_table('classifications',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('priority', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('labeled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Customer','Internal','Vendor','Meeting','Spam')", name='ck_classifications_category'),
    sa.CheckConstraint("priority IN ('Urgent','Normal','Low')", name='ck_classifications_priority'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_index('ix_classifications_user_priority', 'classifications', ['user_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_classifications_user_priority', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('ix_gmail_tokens_watch_expiration', table_name='gmail_tokens')
    op.drop_table('gmail_tokens')
    op.drop_table('gmail_labels')
    op.drop_index('ix_emails_user_received_at', table_name='emails')
    op.drop_index('ix_emails_user_pending', table_name='emails', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('emails')
    # ### end Alembic commands ###
